---
# Copy the backup shell script to the target server. Adjust the source and destination paths as needed.
# Schedule a cron job to run the backup script daily at 9am. Adjust the job, minute, hour, and user parameters as needed

- name: Copy backup shell script and schedule cron job
  hosts: all
  become: true
  tasks:
    - name: Copy backup shell script
      copy:
        src: /files/backup_script.sh
        dest: /opt/backup_script.sh
        mode: 0755

    - name: Schedule cron job for backup
      cron:
        name: "Daily Backup"
        job: "/opt/backup_script.sh"
        minute: 0
        hour: 9
        user: root
