---
# This playbook installs the chrony package and copies the chrony configuration file to configure the chronyd service on target servers. It ensures that the service is started and enabled to run automatically on system boot.
# Modify the paths as per your environment and target server configurations.

- name: Install and configure chronyd
  hosts: all
  become: true
  tasks:
    - name: Install chrony package
      package:
        name: chrony
        state: present

    - name: Copy chrony configuration file
      copy:
        src: /files/chrony.conf
        dest: /etc/chrony.conf
        owner: root
        group: root
        mode: 0644

    - name: Start and enable chronyd service
      service:
        name: chronyd
        state: started
        enabled: true
